name: github pages

on:
    push:
        branches:
          - master

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            shell: bash
            run: |
              git submodule sync --recursive
              git submodule update --init --force --recursive --depth=1

          - name: Setup Hugo
            uses: peaceiris/actions-hugo@v2
            with:
                hugo-version: '0.62.2'
                extended: true

          - name: Build
            run: hugo --gc --minify --cleanDestinationDir

          - name: Deploy
            uses: peaceiris/actions-gh-pages@v2
            env:
              ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
              EXTERNAL_REPOSITORY: hellupline/hellupline.github.io
              PUBLISH_BRANCH: master
              PUBLISH_DIR: ./public
